//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Almacenamiento_TP.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestion_de_Almacenamiento_TP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _172971664_paquete_de_devolución_de_garabato_dibujado_a_mano_o_vector_de_ilustración_de_pedido {
            get {
                object obj = ResourceManager.GetObject("172971664-paquete-de-devolución-de-garabato-dibujado-a-mano-o-vector-de-ilustraci" +
                        "ón-de-pedido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _181001636_contorno_relleno_icono_de_vehículo_de_camión_de_carga_de_entrega_aislado_sobre_fondo_blanco {
            get {
                object obj = ResourceManager.GetObject("181001636-contorno-relleno-icono-de-vehículo-de-camión-de-carga-de-entrega-aislad" +
                        "o-sobre-fondo-blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _186244406_icon_distribution_suitable_for_education_symbol_two_tone_style_simple_design_editable_design {
            get {
                object obj = ResourceManager.GetObject("186244406-icon-distribution-suitable-for-education-symbol-two-tone-style-simple-d" +
                        "esign-editable-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _186244406_icon_distribution_suitable_for_education_symbol_two_tone_style_simple_design_editable_design1 {
            get {
                object obj = ResourceManager.GetObject("186244406-icon-distribution-suitable-for-education-symbol-two-tone-style-simple-d" +
                        "esign-editable-design1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _211289249_opening_a_box_receiving_a_delivery_or_packing_stuff_to_move_pixel_perfect_icon {
            get {
                object obj = ResourceManager.GetObject("211289249-opening-a-box-receiving-a-delivery-or-packing-stuff-to-move-pixel-perfe" +
                        "ct-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_65dp_E3E3E3_FILL0_wght700_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("lock_65dp_E3E3E3_FILL0_wght700_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logotipo_de_icono_camión_entrega_simple_vector_rápido_envío_imagen_colorido_logo_pictograma_aislado_en_fondo_blanco_203082949 {
            get {
                object obj = ResourceManager.GetObject("logotipo-de-icono-camión-entrega-simple-vector-rápido-envío-imagen-colorido-logo-" +
                        "pictograma-aislado-en-fondo-blanco-203082949", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
